server:
  port: 6060

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/posts/**
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/services/**
        - id: competence-service
          uri: lb://COMPETENCE-SERVICE
          predicates:
            - Path=/competences/**
        - id: competence-service
          uri: lb://COMPETENCE-SERVICE
          predicates:
            - Path=/familles/**
        - id: competence-service
          uri: lb://COMPETENCE-SERVICE
          predicates:
            - Path=/indicateurs/**
        - id: evaluation-service
          uri: lb://EVALUATION-SERVICE
          predicates:
            - Path=/evaluation/**
        - id: evaluation-service
          uri: lb://EVALUATION-SERVICE
          predicates:
            - Path=/postcompetence/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/gestion-competence"