spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: employee-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

